export const SET_T0T1 = 'SET_T0T1'
export const SET_T1E = 'SET_T1E'
export const SET_ET2 = 'SET_ET2'
export const SET_T2T3 = 'SET_T2T3'

export const SET_DATE_COLUMN = 'SET_DATE_COLUMN'
export const SET_OPERATION_COLUMN = 'SET_OPERATION_COLUMN'

export const CREATE_EVENT = 'CREATE_EVENT'
export const UPDATE_EVENT = 'UPDATE_EVENT'
export const DELETE_EVENT = 'DELETE_EVENT'
export const SELECT_EVENT = 'SELECT_EVENT'
export const DESELECT_EVENT = 'DESELECT_EVENT'

export const CREATE_STOCK = 'CREATE_STOCK'
export const UPDATE_STOCK = 'UPDATE_STOCK'
export const DELETE_STOCK = 'DELETE_STOCK'
export const SELECT_STOCK = 'SELECT_STOCK'

export const CREATE_ANALYSIS = 'CREATE_ANALYSIS'
export const UPDATE_ANALYSIS = 'UPDATE_ANALYSIS'
export const DELETE_ANALYSIS = 'DELETE_ANALYSIS'

export const SHOW_SETTING = 'SHOW_SETTING'
export const HIDE_SETTING = 'HIDE_SETTING'

export const SET_DEFAULT_EVENT_DATE_FORMAT = 'SET_DEFAULT_EVENT_DATE_FORMAT'
